@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create-account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Marcelo2",
    "email": "marcelo2@teste.com.br",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "marcelo2@teste.com.br",
    "password": "123456"
}

###

# @name create-question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta 3",
    "content": "Conteúdo da pergunta 3"
}

###

# @name fetch-recent-questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
